// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import CustomAutocompleteController from "./custom_autocomplete_controller"
application.register("custom-autocomplete", CustomAutocompleteController)


// import { application } from "./application"
// import Autocomplete from "stimulus-autocomplete"

// application.register("autocomplete", Autocomplete)

